name: test

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'playground/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'playground/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.12.2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test:unit

      - name: Build
        run: pnpm run build

      - uses: codecov/codecov-action@v2
